workflows:
  ios-expo-workflow:
    name: iOS Force Build
    instance_type: mac_mini_m1
    environment:
      groups:
        - expo
        - apple
      node: latest
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Install EAS CLI
        script: npm install -g eas-cli
      - name: Force Production Build
        script: |
          # 1. إعداد المفتاح p8
          echo "$APP_STORE_CONNECT_P8" > ./AuthKey_XLB4TLKY66.p8

          # 2. حقن المتغيرات مباشرة في بيئة العمل (تخطي الـ 2FA والملفات المحلية)
          export EXPO_ASC_API_KEY_PATH="./AuthKey_XLB4TLKY66.p8"
          export EXPO_ASC_API_KEY_ID="XLB4TLKY66"
          export EXPO_ASC_API_KEY_ISSUER_ID="990d71a4-1bd0-4ca7-a3f9-417d062f6ac1"
          export EXPO_APPLE_TEAM_ID="9MLYHHLY82"
          
          export EAS_NO_VCS=1
          export EAS_BUILD_NO_EXPO_GO_WARNING=true

          # 3. الضربة القاضية: أمر واحد يبني ويرفع للسحاب (بدون --local)
          # هذا الأمر سيستخدم حساب Expo الجديد الخاص بك لعمل البناء على سيرفرات Expo 
          # وبما أننا زودناه بالمفاتيح، سيتخطى طلب الـ SMS تلقائياً
          eas build --platform ios --profile production --non-interactive --no-wait
