import { StyleSheet } from "react-native"

export const createCalculationsStyles = (theme: any) =>
  StyleSheet.create({
    container: {
      flex: 1,
    },
    sliderContainer: {
      paddingTop: 4,
      paddingBottom: 0,
      borderBottomWidth: 0,
      height: 110,
      overflow: "hidden",
    },
    sliderScrollHint: {
      position: "absolute",
      right: 6,
      top: 22,
      zIndex: 50,
    },
    sliderScrollHintButton: {
      width: 30,
      height: 30,
      borderRadius: 15,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: theme.isDark ? 0 : 0.14,
      shadowRadius: 16,
      elevation: theme.isDark ? 0 : 8,
    },
    sliderListContent: {
      paddingHorizontal: 6,
    },
    sliderItemSeparator: {
      width: 3,
    },
    contentScroll: {
      flex: 1,
    },
    contentContainer: {
      flexGrow: 1,
      padding: 14,
      paddingBottom: 140,
    },
    inputsContainer: {
      width: "100%",
    },
    modeRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      marginBottom: 10,
    },
    modeButton: {
      flex: 1,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.surface2,
      paddingVertical: 10,
      paddingHorizontal: 10,
      borderRadius: 12,
      alignItems: "center",
    },
    modeButtonActive: {
      borderColor: "rgba(240,140,33,0.40)",
      backgroundColor: "rgba(240,140,33,0.16)",
    },
    modeButtonText: {
      fontSize: 11,
      fontWeight: "900",
      color: theme.colors.text,
    },
    calcPreviewContainer: {
      width: "100%",
      marginTop: 0,
      marginBottom: 0,
      padding: 0,
      backgroundColor: theme.colors.surface,
      borderRadius: 14,
      borderWidth: 0,
      borderColor: "transparent",
      alignItems: "center",
      justifyContent: "center",
    },
    calcPreviewImage: {
      width: "100%",
      height: 150,
    },
    formTwoColRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 10,
    },
    formLeftCol: {
      flex: 1,
      minWidth: 0,
    },
    formRightCol: {
      width: 120,
      minWidth: 96,
      alignItems: "center",
    },
    densityRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      marginBottom: 12,
    },
    densitySelect: {
      flex: 1,
      minWidth: 0,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.surface2,
      minHeight: 42,
      paddingHorizontal: 8,
      paddingVertical: 6,
      borderRadius: 12,
      justifyContent: "center",
    },
    densitySelectUnit: {
      flexShrink: 0,
      width: 74,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.surface2,
      height: 42,
      paddingHorizontal: 6,
      borderRadius: 12,
      alignItems: "center",
      justifyContent: "center",
    },
    densitySelectText: {
      fontSize: 11,
      fontWeight: "800",
      color: theme.colors.text,
    },
    densityResetButton: {
      height: 42,
      paddingHorizontal: 6,
      alignItems: "center",
      justifyContent: "center",
      flexShrink: 0,
    },
    dropdownAnchor: {
      ...StyleSheet.absoluteFillObject,
      opacity: 0,
      zIndex: 200,
    },
    dropdownContainer: {
      borderRadius: 14,
      paddingVertical: 4,
      paddingHorizontal: 4,
      zIndex: 200,
      elevation: 12,
      shadowColor: "#000",
      shadowOpacity: 0.18,
      shadowRadius: 18,
      shadowOffset: { width: 0, height: 10 },
    },
    dropdownHiddenText: {
      height: 0,
      opacity: 0,
    },
    inputRow: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 10,
    },
    inputLabel: {
      flex: 1,
      fontSize: 13,
      fontWeight: "900",
    },
    input: {
      flex: 2,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.surface2,
      height: 42,
      paddingHorizontal: 12,
      borderRadius: 12,
      color: theme.colors.text,
    },
    inputWithPrefix: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      borderWidth: 1,
      borderColor: theme.colors.border,
      borderRadius: 12,
      overflow: "hidden",
      height: 42,
      backgroundColor: theme.colors.surface2,
      direction: "ltr",
    },
    inputPrefix: {
      height: "100%",
      minWidth: 25,
      paddingHorizontal: 6,
      alignItems: "center",
      justifyContent: "center",
      borderRightWidth: 0,
      borderRightColor: "transparent",
      backgroundColor: theme.colors.surface2,
    },
    inputPrefixText: {
      fontSize: 12,
      fontWeight: "900",
    },
    inputFlexNoUnit: {
      flex: 1,
      height: 42,
      paddingLeft: 8,
      paddingRight: 10,
      paddingVertical: 0,
      color: theme.colors.text,
      textAlign: "center",
      textAlignVertical: "center",
    },
    priceInputWithCurrency: {
      flex: 2,
      flexDirection: "row",
      alignItems: "center",
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.surface2,
      height: 42,
      paddingHorizontal: 12,
      borderRadius: 12,
    },
    priceInputWithPrefixCurrency: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.surface2,
      height: 42,
      borderRadius: 12,
      overflow: "hidden",
      direction: "ltr",
    },
    priceInput: {
      flex: 1,
      height: 42,
      paddingVertical: 0,
      paddingLeft: 8,
      paddingRight: 10,
      color: theme.colors.text,
      textAlign: "center",
      textAlignVertical: "center",
    },
    priceInputCurrency: {
      marginLeft: 8,
      paddingRight: 12,
      fontSize: 12,
      fontWeight: "900",
      color: theme.colors.textSecondary,
    },
    inputWithUnit: {
      flex: 2,
      flexDirection: "row",
      alignItems: "center",
      borderWidth: 1,
      borderColor: theme.colors.border,
      borderRadius: 12,
      overflow: "hidden",
      height: 42,
      backgroundColor: theme.colors.surface2,
      direction: "ltr",
    },
    inputFlex: {
      flex: 1,
      height: 42,
      paddingLeft: 8,
      paddingRight: 10,
      paddingVertical: 0,
      color: theme.colors.text,
      textAlign: "center",
      textAlignVertical: "center",
    },
    unitButton: {
      height: "100%",
      width: 58,
      alignItems: "center",
      justifyContent: "center",
      borderLeftWidth: 1,
      borderLeftColor: theme.colors.border,
      backgroundColor: theme.colors.surface2,
    },
    unitButtonText: {
      fontSize: 12,
      fontWeight: "800",
      color: theme.colors.textSecondary,
    },
    calculateButton: {
      backgroundColor: theme.colors.secondary,
      paddingVertical: 14,
      paddingHorizontal: 16,
      borderRadius: 14,
      alignItems: "center",
      marginTop: 10,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: theme.isDark ? 0 : 0.16,
      shadowRadius: 18,
      elevation: theme.isDark ? 0 : 10,
    },
    calculateButtonText: {
      color: "#ffffff",
      fontSize: 16,
      fontWeight: "800",
    },
    resultsContainer: {
      marginTop: 14,
      padding: 12,
      backgroundColor: theme.colors.surface,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    resultsActionsRow: {
      marginTop: 10,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "flex-end",
      gap: 10,
    },
    resultsActionButton: {
      width: 34,
      height: 34,
      borderRadius: 17,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.colors.surface2,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    calcActionsRow: {
      marginTop: 10,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 12,
    },
    calcActionButton: {
      width: 38,
      height: 38,
      borderRadius: 19,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.colors.surface2,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    resultRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      marginBottom: 6,
    },
    resultLabelGroup: {
      flex: 1,
      minWidth: 0,
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    resultLabelGroupRtl: {
      flex: 0,
      flexShrink: 0,
      justifyContent: "flex-end",
    },
    resultLabelText: {
      fontSize: 13,
      fontWeight: "600",
      marginBottom: 0,
      flexShrink: 1,
    },
    resultLabelTextRtl: {
      textAlign: "right",
      writingDirection: "rtl",
    },
    resultValueText: {
      fontSize: 13,
      fontWeight: "700",
      marginBottom: 0,
      flexShrink: 0,
    },
    resultValueTextRtl: {
      flex: 1,
      textAlign: "right",
      writingDirection: "ltr",
    },
    resultCopyButton: {
      width: 22,
      height: 22,
      borderRadius: 11,
      alignItems: "center",
      justifyContent: "center",
      flexShrink: 0,
    },
    resultText: {
      fontSize: 13,
      fontWeight: "600",
      marginBottom: 6,
    },
    currencyPillText: {
      fontSize: 13,
      fontWeight: "400",
      color: theme.colors.text,
    },
    itemButton: {
      width: 88,
      paddingVertical: 5,
      paddingHorizontal: 6,
      alignItems: "center",
      borderRadius: 10,
    },
    itemImageWrapper: {
      width: 64,
      height: 64,
      borderRadius: 16,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.colors.surface,
      borderWidth: 0,
      borderColor: "transparent",
    },
    itemImageWrapperActive: {
      backgroundColor: "rgba(240,140,33,0.16)",
      borderWidth: 1,
      borderColor: "rgba(240,140,33,0.40)",
    },
    itemImage: {
      width: 50,
      height: 50,
    },
    itemLabel: {
      marginTop: 3,
      fontSize: 12,
      fontWeight: "700",
      width: "100%",
      textAlign: "center",
      lineHeight: 14,
      minHeight: 28,
    },
    itemLabelSub: {
      fontSize: 10,
      fontWeight: "600",
      textAlign: "center",
    },
    modalBackdrop: {
      flex: 1,
      backgroundColor: theme.isDark ? "rgba(0,0,0,0.55)" : "rgba(0,0,0,0.25)",
    },
    modalCard: {
      position: "absolute",
      borderRadius: 14,
      paddingVertical: 4,
      paddingHorizontal: 4,
      borderWidth: 1,
      borderColor: theme.colors.border,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.18,
      shadowRadius: 18,
      elevation: 12,
    },
    modalCardCompact: {
      paddingVertical: 2,
      paddingHorizontal: 2,
    },
    modalTitle: {
      fontSize: 12,
      fontWeight: "900",
      marginBottom: 6,
    },
    modalList: {
      width: "100%",
    },
    modalListContent: {
      paddingBottom: 0,
    },
    modalListContentCompact: {
      paddingBottom: 0,
    },
    modalOption: {
      paddingVertical: 4,
      paddingHorizontal: 8,
      borderRadius: 8,
      marginBottom: 2,
      borderWidth: 0,
      backgroundColor: "transparent",
    },
    modalOptionCompact: {
      paddingVertical: 5,
      paddingHorizontal: 4,
      marginBottom: 3,
      borderRadius: 6,
    },
    modalOptionActive: {
      backgroundColor: "rgba(240,140,33,0.16)",
    },
    modalOptionText: {
      fontSize: 12,
      fontWeight: "700",
      lineHeight: 16,
    },
    modalOptionRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      justifyContent: "space-between",
      gap: 8,
    },
    modalOptionRowCompact: {
      gap: 2,
    },
    modalOptionLeftText: {
      flex: 1,
      minWidth: 0,
      fontSize: 12,
      fontWeight: "700",
      lineHeight: 16,
    },
    modalOptionLeftTextCompact: {
      lineHeight: 14,
    },
    modalOptionRightText: {
      flexShrink: 0,
      minWidth: 54,
      fontSize: 12,
      fontWeight: "800",
      lineHeight: 16,
      textAlign: "right",
      marginLeft: 8,
    },
    modalOptionRightTextCompact: {
      minWidth: 40,
      marginLeft: 2,
      lineHeight: 14,
    },
    modalOptionTextActive: {
      color: theme.colors.secondary,
    },
  })
