import { StyleSheet } from "react-native"

export const createCalculationsStyles = (theme: any) =>
  StyleSheet.create({
    container: {
      flex: 1,
    },
    sliderContainer: {
      paddingTop: 4,
      paddingBottom: 6,
      borderBottomWidth: 0,
    },
    contentScroll: {
      flex: 1,
    },
    contentContainer: {
      flexGrow: 1,
      padding: 14,
      paddingBottom: 140,
    },
    inputsContainer: {
      width: "100%",
    },
    modeRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      marginBottom: 10,
    },
    modeButton: {
      flex: 1,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.surface2,
      paddingVertical: 10,
      paddingHorizontal: 10,
      borderRadius: 12,
      alignItems: "center",
    },
    modeButtonActive: {
      borderColor: "rgba(240,140,33,0.40)",
      backgroundColor: "rgba(240,140,33,0.16)",
    },
    modeButtonText: {
      fontSize: 11,
      fontWeight: "900",
      color: theme.colors.text,
    },
    calcPreviewContainer: {
      marginTop: -10,
      marginBottom: 4,
      padding: 0,
      backgroundColor: theme.colors.surface,
      borderRadius: 14,
      borderWidth: 0,
      borderColor: "transparent",
      alignItems: "center",
      justifyContent: "center",
    },
    calcPreviewImage: {
      width: "100%",
      height: 160,
    },
    densityRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      marginBottom: 12,
    },
    densitySelect: {
      flex: 1,
      minWidth: 0,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.surface2,
      height: 42,
      paddingHorizontal: 12,
      borderRadius: 12,
      justifyContent: "center",
    },
    densitySelectUnit: {
      width: 92,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.surface2,
      height: 42,
      paddingHorizontal: 10,
      borderRadius: 12,
      justifyContent: "center",
    },
    densitySelectText: {
      fontSize: 11,
      fontWeight: "800",
      color: theme.colors.text,
    },
    dropdownAnchor: {
      ...StyleSheet.absoluteFillObject,
      opacity: 0,
      zIndex: 200,
    },
    dropdownContainer: {
      borderRadius: 14,
      paddingVertical: 4,
      paddingHorizontal: 4,
      zIndex: 200,
      elevation: 12,
      shadowColor: "#000",
      shadowOpacity: 0.18,
      shadowRadius: 18,
      shadowOffset: { width: 0, height: 10 },
    },
    dropdownHiddenText: {
      height: 0,
      opacity: 0,
    },
    inputRow: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 10,
    },
    inputLabel: {
      flex: 1,
      fontSize: 13,
      fontWeight: "900",
    },
    input: {
      flex: 2,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.surface2,
      height: 42,
      paddingHorizontal: 12,
      borderRadius: 12,
      color: theme.colors.text,
    },
    priceInputWithCurrency: {
      flex: 2,
      flexDirection: "row",
      alignItems: "center",
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.surface2,
      height: 42,
      paddingHorizontal: 12,
      borderRadius: 12,
    },
    priceInput: {
      flex: 1,
      height: 42,
      paddingVertical: 0,
      color: theme.colors.text,
    },
    priceInputCurrency: {
      marginLeft: 8,
      fontSize: 12,
      fontWeight: "900",
      color: theme.colors.textSecondary,
    },
    inputWithUnit: {
      flex: 2,
      flexDirection: "row",
      alignItems: "center",
      borderWidth: 1,
      borderColor: theme.colors.border,
      borderRadius: 12,
      overflow: "hidden",
      height: 42,
      backgroundColor: theme.colors.surface2,
    },
    inputFlex: {
      flex: 1,
      height: 42,
      paddingHorizontal: 12,
      paddingVertical: 0,
      color: theme.colors.text,
    },
    unitButton: {
      height: "100%",
      width: 58,
      alignItems: "center",
      justifyContent: "center",
      borderLeftWidth: 1,
      borderLeftColor: theme.colors.border,
      backgroundColor: theme.colors.surface2,
    },
    unitButtonText: {
      fontSize: 12,
      fontWeight: "800",
      color: theme.colors.textSecondary,
    },
    calculateButton: {
      backgroundColor: theme.colors.secondary,
      paddingVertical: 14,
      paddingHorizontal: 16,
      borderRadius: 14,
      alignItems: "center",
      marginTop: 10,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: theme.isDark ? 0 : 0.16,
      shadowRadius: 18,
      elevation: theme.isDark ? 0 : 10,
    },
    calculateButtonText: {
      color: "#ffffff",
      fontSize: 16,
      fontWeight: "800",
    },
    resultsContainer: {
      marginTop: 14,
      padding: 12,
      backgroundColor: theme.colors.surface,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    resultRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      marginBottom: 6,
    },
    resultText: {
      fontSize: 13,
      marginBottom: 6,
    },
    currencyPillText: {
      fontSize: 13,
      fontWeight: "400",
      color: theme.colors.text,
    },
    itemButton: {
      paddingVertical: 8,
      paddingHorizontal: 8,
      alignItems: "center",
      marginHorizontal: 5,
      borderRadius: 10,
    },
    itemImageWrapper: {
      width: 58,
      height: 58,
      borderRadius: 16,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.colors.surface,
      borderWidth: 0,
      borderColor: "transparent",
    },
    itemImageWrapperActive: {
      backgroundColor: "rgba(240,140,33,0.16)",
      borderWidth: 1,
      borderColor: "rgba(240,140,33,0.40)",
    },
    itemImage: {
      width: 44,
      height: 44,
    },
    itemLabel: {
      marginTop: 3,
      fontSize: 12,
      fontWeight: "700",
    },
    modalBackdrop: {
      flex: 1,
      backgroundColor: theme.isDark ? "rgba(0,0,0,0.55)" : "rgba(0,0,0,0.25)",
    },
    modalCard: {
      position: "absolute",
      borderRadius: 14,
      paddingVertical: 4,
      paddingHorizontal: 4,
      borderWidth: 1,
      borderColor: theme.colors.border,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.18,
      shadowRadius: 18,
      elevation: 12,
    },
    modalCardCompact: {
      paddingVertical: 2,
      paddingHorizontal: 2,
    },
    modalTitle: {
      fontSize: 12,
      fontWeight: "900",
      marginBottom: 6,
    },
    modalList: {
      width: "100%",
    },
    modalListContent: {
      paddingBottom: 0,
    },
    modalListContentCompact: {
      paddingBottom: 0,
    },
    modalOption: {
      paddingVertical: 4,
      paddingHorizontal: 8,
      borderRadius: 8,
      marginBottom: 2,
      borderWidth: 0,
      backgroundColor: "transparent",
    },
    modalOptionCompact: {
      paddingVertical: 5,
      paddingHorizontal: 4,
      marginBottom: 3,
      borderRadius: 6,
    },
    modalOptionActive: {
      backgroundColor: "rgba(240,140,33,0.16)",
    },
    modalOptionText: {
      fontSize: 12,
      fontWeight: "700",
      lineHeight: 16,
    },
    modalOptionRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      justifyContent: "space-between",
      gap: 8,
    },
    modalOptionRowCompact: {
      gap: 2,
    },
    modalOptionLeftText: {
      flex: 1,
      minWidth: 0,
      fontSize: 12,
      fontWeight: "700",
      lineHeight: 16,
    },
    modalOptionLeftTextCompact: {
      lineHeight: 14,
    },
    modalOptionRightText: {
      flexShrink: 0,
      minWidth: 54,
      fontSize: 12,
      fontWeight: "800",
      lineHeight: 16,
      textAlign: "right",
      marginLeft: 8,
    },
    modalOptionRightTextCompact: {
      minWidth: 40,
      marginLeft: 2,
      lineHeight: 14,
    },
    modalOptionTextActive: {
      color: theme.colors.secondary,
    },
  })
