// Currency mapping for 62+ countries with symbols and codes
export const CURRENCY_MAP: Record<string, { symbol: string; code: string }> = {
  SA: { symbol: "﷼", code: "SAR" },
  AE: { symbol: "د.إ", code: "AED" },
  KW: { symbol: "د.ك", code: "KWD" },
  QA: { symbol: "ر.ق", code: "QAR" },
  BH: { symbol: "د.ب", code: "BHD" },
  OM: { symbol: "ر.ع.", code: "OMR" },
  JO: { symbol: "د.ا", code: "JOD" },
  LB: { symbol: "ل.ل", code: "LBP" },
  SY: { symbol: "ل.س", code: "SYP" },
  EG: { symbol: "ج.م", code: "EGP" },
  IQ: { symbol: "ع.د", code: "IQD" },
  PS: { symbol: "₪", code: "ILS" },
  IL: { symbol: "₪", code: "ILS" },
  TR: { symbol: "₺", code: "TRY" },
  IR: { symbol: "ریال", code: "IRR" },
  GB: { symbol: "£", code: "GBP" },
  DE: { symbol: "€", code: "EUR" },
  FR: { symbol: "€", code: "EUR" },
  IT: { symbol: "€", code: "EUR" },
  ES: { symbol: "€", code: "EUR" },
  NL: { symbol: "€", code: "EUR" },
  BE: { symbol: "€", code: "EUR" },
  AT: { symbol: "€", code: "EUR" },
  CH: { symbol: "CHF", code: "CHF" },
  SE: { symbol: "kr", code: "SEK" },
  NO: { symbol: "kr", code: "NOK" },
  DK: { symbol: "kr", code: "DKK" },
  PL: { symbol: "z2", code: "PLN" },
  RU: { symbol: "₽", code: "RUB" },
  UA: { symbol: "₴", code: "UAH" },
  CZ: { symbol: "Kč", code: "CZK" },
  HU: { symbol: "Ft", code: "HUF" },
  RO: { symbol: "lei", code: "RON" },
  GR: { symbol: "€", code: "EUR" },
  PT: { symbol: "€", code: "EUR" },
  IN: { symbol: "₹", code: "INR" },
  CN: { symbol: "¥", code: "CNY" },
  JP: { symbol: "¥", code: "JPY" },
  KR: { symbol: "₩", code: "KRW" },
  TH: { symbol: "฿", code: "THB" },
  MY: { symbol: "RM", code: "MYR" },
  SG: { symbol: "S$", code: "SGD" },
  PH: { symbol: "₱", code: "PHP" },
  VN: { symbol: "₫", code: "VND" },
  ID: { symbol: "Rp", code: "IDR" },
  PK: { symbol: "₨", code: "PKR" },
  BD: { symbol: "৳", code: "BDT" },
  LK: { symbol: "Rs", code: "LKR" },
  US: { symbol: "$", code: "USD" },
  CA: { symbol: "C$", code: "CAD" },
  MX: { symbol: "$", code: "MXN" },
  BR: { symbol: "R$", code: "BRL" },
  AR: { symbol: "$", code: "ARS" },
  CL: { symbol: "$", code: "CLP" },
  CO: { symbol: "$", code: "COP" },
  PE: { symbol: "S/", code: "PEN" },
  VE: { symbol: "Bs", code: "VES" },
  EC: { symbol: "$", code: "USD" },
  ZA: { symbol: "R", code: "ZAR" },
  NG: { symbol: "₦", code: "NGN" },
  KE: { symbol: "KSh", code: "KES" },
  ET: { symbol: "Br", code: "ETB" },
  MA: { symbol: "د.م.", code: "MAD" },
  DZ: { symbol: "د.ج", code: "DZD" },
  TN: { symbol: "د.ت", code: "TND" },
  GH: { symbol: "₵", code: "GHS" },
  TZ: { symbol: "TSh", code: "TZS" },
  AU: { symbol: "A$", code: "AUD" },
  NZ: { symbol: "NZ$", code: "NZD" },
}

export const DEFAULT_COUNTRY_CODE = "SA"
export const DEFAULT_CURRENCY = CURRENCY_MAP[DEFAULT_COUNTRY_CODE]

export function getCurrencyByCountry(countryCode: string) {
  return CURRENCY_MAP[countryCode] || DEFAULT_CURRENCY
}
