import { StyleSheet } from "react-native"

export const calculatorStyles = StyleSheet.create({
  cardWrapper: {
    marginTop: 0,
    marginHorizontal: 16,
    position: "relative",
  },
  feedbackBanner: {
    position: "absolute",
    bottom: 350,
    alignSelf: "center",
    zIndex: 40,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 999,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  feedbackBannerSuccess: {
    backgroundColor: "rgba(22,163,74,0.08)",
  },
  feedbackBannerError: {
    backgroundColor: "rgba(220,38,38,0.08)",
  },
  feedbackBannerText: {
    fontSize: 13,
    color: "#166534",
    fontWeight: "600",
  },
  feedbackBannerTextError: {
    color: "#991b1b",
  },
  card: {
    marginTop: 0,
    marginBottom: 0,
    padding: 12,
    borderRadius: 16,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#e5e7eb",
    overflow: "hidden",
  },
  title: {
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 8,
    color: "#302C6D",
    textAlign: "center",
  },
  section: {
    marginTop: 8,
    paddingVertical: 4,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "#e5e7eb",
  },
  dimsHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  dimsHeaderButtons: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
    minWidth: 0,
    justifyContent: "flex-end",
    flexShrink: 1,
  },
  dimsHeaderControl: {
    width: 60,
  },
  dimsHeaderControlWide: {
    flex: 1,
    minWidth: 130,
    alignItems: "flex-end",
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  label: {
    flex: 1,
    fontSize: 13,
    color: "#374151",
  },
  value: {
    fontSize: 13,
    fontWeight: "700",
    color: "#b91c1c",
  },
  totalPriceValueContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    position: "relative",
  },
  currencyPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: "#fff8ef",
  },
  currencyPillText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#b91c1c",
  },
  priceInputWithCurrency: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#d1d5db",
    backgroundColor: "#ffffff",
    paddingHorizontal: 8,
    paddingVertical: 0,
    height: 32,
    minWidth: 90,
  },
  priceInput: {
    flex: 1,
    height: 32,
    fontSize: 13,
    color: "#111827",
    textAlign: "center",
    textAlignVertical: "center",
    includeFontPadding: false,
    paddingVertical: 0,
    writingDirection: "ltr",
  },
  priceInputCurrency: {
    marginLeft: 8,
    fontSize: 12,
    fontWeight: "700",
    color: "#9ca3af",
  },
  currencyDropdownMenu: {
    marginTop: 6,
    right: 0,
  },
  input: {
    minWidth: 90,
    paddingHorizontal: 8,
    paddingVertical: 0,
    height: 32,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#d1d5db",
    textAlign: "center",
    textAlignVertical: "center",
    fontSize: 13,
    color: "#111827",
    backgroundColor: "#ffffff",
    includeFontPadding: false,
    writingDirection: "ltr",
  },
  dimsInputWithUnit: {
    minWidth: 110,
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#d1d5db",
    backgroundColor: "#ffffff",
    paddingHorizontal: 8,
    paddingVertical: 0,
  },
  dimsInput: {
    flex: 1,
    fontSize: 12,
    color: "#111827",
    textAlign: "left",
    paddingVertical: 0,
    height: 32,
    textAlignVertical: "center",
    includeFontPadding: false,
  },
  dimsInputUnit: {
    marginLeft: 8,
    fontSize: 11,
    color: "#6b7280",
    fontWeight: "600",
  },
  inputWithDropdown: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#d1d5db",
    backgroundColor: "#ffffff",
    position: "relative",
    width: 90,
  },
  inputFlex: {
    paddingHorizontal: 8,
    paddingVertical: 0,
    height: 32,
    fontSize: 13,
    color: "#111827",
    textAlign: "center",
    textAlignVertical: "center",
    includeFontPadding: false,
    flex: 1,
    minWidth: 0,
    borderTopLeftRadius: 8,
    borderBottomLeftRadius: 8,
    writingDirection: "ltr",
  },
  dropdownButton: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderLeftWidth: 1,
    borderLeftColor: "#d1d5db",
    backgroundColor: "#ffffff",
    borderTopRightRadius: 8,
    borderBottomRightRadius: 8,
  },
  dropdownButtonText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#302C6D",
  },
  dropdownMenu: {
    position: "absolute",
    top: "100%",
    right: 0,
    marginTop: 4,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    backgroundColor: "#ffffff",
    paddingVertical: 4,
    paddingHorizontal: 4,
    zIndex: 20,
    elevation: 3,
  },
  dropdownMenuFullWidth: {
    right: undefined,
    left: 28,
    width: "100%",
  },
  densityDropdownMenu: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    backgroundColor: "#ffffff",
    paddingVertical: 0,
    paddingHorizontal: 8,
    zIndex: 200,
    elevation: 12,
    shadowColor: "#000",
    shadowOpacity: 0.18,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
  },
  densityDropdownHeader: {
    height: 24,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#ffffff",
    borderBottomWidth: 1,
    borderBottomColor: "#f3f4f6",
  },
  densityDropdownHeaderLeft: {
    fontSize: 11,
    fontWeight: "600",
    color: "#6b7280",
    flex: 1,
  },
  densityDropdownHeaderRight: {
    fontSize: 11,
    fontWeight: "600",
    color: "#6b7280",
    width: 60,
    textAlign: "right",
  },
  densityDropdownAnchor: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0,
    zIndex: 200,
  },
  dropdownHiddenText: {
    fontSize: 1,
    lineHeight: 1,
    height: 0,
    color: "transparent",
    padding: 0,
    margin: 0,
  },
  densityDropdownItem: {
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  dropdownItem: {
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  dropdownItemText: {
    fontSize: 12,
    color: "#374151",
  },
  dropdownItemSelected: {
    backgroundColor: "#ffedd5",
  },
  dropdownItemTextActive: {
    color: "#302C6D",
    fontWeight: "600",
  },
  dimsDropdownWrapper: {
    position: "relative",
    zIndex: 60,
  },
  dimDropdownButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#d1d5db",
    backgroundColor: "#ffffff",
    width: "100%",
  },
  dimDropdownLabel: {
    fontSize: 11,
    color: "#6b7280",
    marginRight: 4,
  },
  dimDropdownValue: {
    fontSize: 12,
    fontWeight: "600",
    color: "#302C6D",
    flex: 1,
    textAlign: "center",
  },
  dimDropdownButtonWide: {
    minWidth: 0,
    justifyContent: "space-between",
    width: 130,
    alignSelf: "flex-end",
  },
  dimDropdownButtonUnit: {
    minWidth: 90,
  },
  dimDropdownIcon: {
    marginLeft: "auto",
  },
  densityItemRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  densityItemLabel: {
    fontSize: 12,
    color: "#374151",
    flexShrink: 1,
  },
  densityItemValue: {
    fontSize: 12,
    fontWeight: "600",
    color: "#302C6D",
    width: 60,
    textAlign: "right",
    marginLeft: 12,
    flexShrink: 0,
  },
  densityHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#e5e7eb",
  },
  densityHeaderText: {
    fontSize: 11,
    fontWeight: "600",
    color: "#6b7280",
  },
  densityScroll: {
    height: 220,
    flexGrow: 0,
  },
  densityItemLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    minWidth: 0,
  },
  densityCheckIcon: {
    marginRight: 6,
  },
  densityItemLabelSelected: {
    color: "#ea580c",
    fontWeight: "600",
  },
  densityItemValueSelected: {
    color: "#ea580c",
    fontWeight: "700",
  },
  unitDropdownItemSelected: {
    backgroundColor: "#ffedd5",
    borderRadius: 6,
  },
  unitDropdownItemTextActive: {
    color: "#ea580c",
    fontWeight: "600",
  },
  lengthLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 8,
  },
  linearWeightLabelContainer: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    minWidth: 0,
  },
  linearWeightToggleButton: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#e5e7eb",
    backgroundColor: "#ffffff",
  },
  copyIconButton: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
  },
  lengthLabelText: {
    fontSize: 13,
    color: "#374151",
  },
  lengthQuickButton: {
    minWidth: 70,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#000000",
    backgroundColor: "#000000",
    alignItems: "center",
    justifyContent: "center",
  },
  lengthQuickButtonText: {
    fontSize: 12,
    color: "#ffffff",
    fontWeight: "700",
  },
  resetButton: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: "#ef4444",
    alignItems: "center",
  },
  resetButtonText: {
    fontSize: 11,
    fontWeight: "600",
    color: "#ffffff",
  },
  actionsRow: {
    marginTop: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  iconButtonWrapper: {
    alignItems: "center",
    marginRight: 8,
  },
  iconCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#000000",
    alignItems: "center",
    justifyContent: "center",
  },
  iconCircleWarning: {
    backgroundColor: "#000000",
  },
  iconLabel: {
    marginTop: 4,
    fontSize: 10,
    color: "#374151",
  },
})
